// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: nmsg.proto

package nmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nmsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payloads    []*NmsgPayload `protobuf:"bytes,1,rep,name=payloads" json:"payloads,omitempty"`
	PayloadCrcs []uint32       `protobuf:"varint,2,rep,name=payload_crcs,json=payloadCrcs" json:"payload_crcs,omitempty"`
	Sequence    *uint32        `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	SequenceId  *uint64        `protobuf:"varint,4,opt,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
}

func (x *Nmsg) Reset() {
	*x = Nmsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nmsg) ProtoMessage() {}

func (x *Nmsg) ProtoReflect() protoreflect.Message {
	mi := &file_nmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nmsg.ProtoReflect.Descriptor instead.
func (*Nmsg) Descriptor() ([]byte, []int) {
	return file_nmsg_proto_rawDescGZIP(), []int{0}
}

func (x *Nmsg) GetPayloads() []*NmsgPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *Nmsg) GetPayloadCrcs() []uint32 {
	if x != nil {
		return x.PayloadCrcs
	}
	return nil
}

func (x *Nmsg) GetSequence() uint32 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

func (x *Nmsg) GetSequenceId() uint64 {
	if x != nil && x.SequenceId != nil {
		return *x.SequenceId
	}
	return 0
}

type NmsgFragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Current  *uint32 `protobuf:"varint,2,req,name=current" json:"current,omitempty"`
	Last     *uint32 `protobuf:"varint,3,req,name=last" json:"last,omitempty"`
	Fragment []byte  `protobuf:"bytes,4,req,name=fragment" json:"fragment,omitempty"`
	Crc      *uint32 `protobuf:"varint,5,opt,name=crc" json:"crc,omitempty"`
}

func (x *NmsgFragment) Reset() {
	*x = NmsgFragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NmsgFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NmsgFragment) ProtoMessage() {}

func (x *NmsgFragment) ProtoReflect() protoreflect.Message {
	mi := &file_nmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NmsgFragment.ProtoReflect.Descriptor instead.
func (*NmsgFragment) Descriptor() ([]byte, []int) {
	return file_nmsg_proto_rawDescGZIP(), []int{1}
}

func (x *NmsgFragment) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NmsgFragment) GetCurrent() uint32 {
	if x != nil && x.Current != nil {
		return *x.Current
	}
	return 0
}

func (x *NmsgFragment) GetLast() uint32 {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return 0
}

func (x *NmsgFragment) GetFragment() []byte {
	if x != nil {
		return x.Fragment
	}
	return nil
}

func (x *NmsgFragment) GetCrc() uint32 {
	if x != nil && x.Crc != nil {
		return *x.Crc
	}
	return 0
}

type NmsgPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid      *uint32 `protobuf:"varint,1,req,name=vid" json:"vid,omitempty"`
	Msgtype  *uint32 `protobuf:"varint,2,req,name=msgtype" json:"msgtype,omitempty"`
	TimeSec  *int64  `protobuf:"varint,3,req,name=time_sec,json=timeSec" json:"time_sec,omitempty"`
	TimeNsec *uint32 `protobuf:"fixed32,4,req,name=time_nsec,json=timeNsec" json:"time_nsec,omitempty"`
	Payload  []byte  `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
	Source   *uint32 `protobuf:"varint,7,opt,name=source" json:"source,omitempty"`
	Operator *uint32 `protobuf:"varint,8,opt,name=operator" json:"operator,omitempty"`
	Group    *uint32 `protobuf:"varint,9,opt,name=group" json:"group,omitempty"`
}

func (x *NmsgPayload) Reset() {
	*x = NmsgPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NmsgPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NmsgPayload) ProtoMessage() {}

func (x *NmsgPayload) ProtoReflect() protoreflect.Message {
	mi := &file_nmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NmsgPayload.ProtoReflect.Descriptor instead.
func (*NmsgPayload) Descriptor() ([]byte, []int) {
	return file_nmsg_proto_rawDescGZIP(), []int{2}
}

func (x *NmsgPayload) GetVid() uint32 {
	if x != nil && x.Vid != nil {
		return *x.Vid
	}
	return 0
}

func (x *NmsgPayload) GetMsgtype() uint32 {
	if x != nil && x.Msgtype != nil {
		return *x.Msgtype
	}
	return 0
}

func (x *NmsgPayload) GetTimeSec() int64 {
	if x != nil && x.TimeSec != nil {
		return *x.TimeSec
	}
	return 0
}

func (x *NmsgPayload) GetTimeNsec() uint32 {
	if x != nil && x.TimeNsec != nil {
		return *x.TimeNsec
	}
	return 0
}

func (x *NmsgPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NmsgPayload) GetSource() uint32 {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return 0
}

func (x *NmsgPayload) GetOperator() uint32 {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return 0
}

func (x *NmsgPayload) GetGroup() uint32 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

var File_nmsg_proto protoreflect.FileDescriptor

var file_nmsg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x6d,
	0x73, 0x67, 0x22, 0x95, 0x01, 0x0a, 0x04, 0x4e, 0x6d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x08, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x4e, 0x6d, 0x73, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x63, 0x72, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x72, 0x63, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x0c, 0x4e, 0x6d,
	0x73, 0x67, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0d, 0x52, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x63, 0x72, 0x63, 0x22, 0xd5, 0x01, 0x0a, 0x0b, 0x4e, 0x6d, 0x73, 0x67, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0d, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x02, 0x28, 0x07,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x73, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
}

var (
	file_nmsg_proto_rawDescOnce sync.Once
	file_nmsg_proto_rawDescData = file_nmsg_proto_rawDesc
)

func file_nmsg_proto_rawDescGZIP() []byte {
	file_nmsg_proto_rawDescOnce.Do(func() {
		file_nmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_nmsg_proto_rawDescData)
	})
	return file_nmsg_proto_rawDescData
}

var file_nmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nmsg_proto_goTypes = []interface{}{
	(*Nmsg)(nil),         // 0: nmsg.Nmsg
	(*NmsgFragment)(nil), // 1: nmsg.NmsgFragment
	(*NmsgPayload)(nil),  // 2: nmsg.NmsgPayload
}
var file_nmsg_proto_depIdxs = []int32{
	2, // 0: nmsg.Nmsg.payloads:type_name -> nmsg.NmsgPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nmsg_proto_init() }
func file_nmsg_proto_init() {
	if File_nmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nmsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NmsgFragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NmsgPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nmsg_proto_goTypes,
		DependencyIndexes: file_nmsg_proto_depIdxs,
		MessageInfos:      file_nmsg_proto_msgTypes,
	}.Build()
	File_nmsg_proto = out.File
	file_nmsg_proto_rawDesc = nil
	file_nmsg_proto_goTypes = nil
	file_nmsg_proto_depIdxs = nil
}
