// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: ipconn.proto

package nmsg_base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto   *uint32 `protobuf:"varint,1,opt,name=proto" json:"proto,omitempty"`
	Srcip   []byte  `protobuf:"bytes,2,opt,name=srcip" json:"srcip,omitempty"`
	Srcport *uint32 `protobuf:"varint,3,opt,name=srcport" json:"srcport,omitempty"`
	Dstip   []byte  `protobuf:"bytes,4,opt,name=dstip" json:"dstip,omitempty"`
	Dstport *uint32 `protobuf:"varint,5,opt,name=dstport" json:"dstport,omitempty"`
}

func (x *IPConn) Reset() {
	*x = IPConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipconn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPConn) ProtoMessage() {}

func (x *IPConn) ProtoReflect() protoreflect.Message {
	mi := &file_ipconn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPConn.ProtoReflect.Descriptor instead.
func (*IPConn) Descriptor() ([]byte, []int) {
	return file_ipconn_proto_rawDescGZIP(), []int{0}
}

func (x *IPConn) GetProto() uint32 {
	if x != nil && x.Proto != nil {
		return *x.Proto
	}
	return 0
}

func (x *IPConn) GetSrcip() []byte {
	if x != nil {
		return x.Srcip
	}
	return nil
}

func (x *IPConn) GetSrcport() uint32 {
	if x != nil && x.Srcport != nil {
		return *x.Srcport
	}
	return 0
}

func (x *IPConn) GetDstip() []byte {
	if x != nil {
		return x.Dstip
	}
	return nil
}

func (x *IPConn) GetDstport() uint32 {
	if x != nil && x.Dstport != nil {
		return *x.Dstport
	}
	return 0
}

var File_ipconn_proto protoreflect.FileDescriptor

var file_ipconn_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x70, 0x63, 0x6f, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x22, 0x7e, 0x0a, 0x06, 0x49, 0x50, 0x43,
	0x6f, 0x6e, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63,
	0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x72, 0x63, 0x69, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x72, 0x63, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x73, 0x74,
	0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x73, 0x74, 0x69, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x64, 0x73, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x73, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x65, 0x63, 0x2f, 0x67, 0x6f, 0x2d, 0x6e, 0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x6d, 0x73, 0x67,
	0x5f, 0x62, 0x61, 0x73, 0x65,
}

var (
	file_ipconn_proto_rawDescOnce sync.Once
	file_ipconn_proto_rawDescData = file_ipconn_proto_rawDesc
)

func file_ipconn_proto_rawDescGZIP() []byte {
	file_ipconn_proto_rawDescOnce.Do(func() {
		file_ipconn_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipconn_proto_rawDescData)
	})
	return file_ipconn_proto_rawDescData
}

var file_ipconn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ipconn_proto_goTypes = []interface{}{
	(*IPConn)(nil), // 0: nmsg.base.IPConn
}
var file_ipconn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipconn_proto_init() }
func file_ipconn_proto_init() {
	if File_ipconn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipconn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipconn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipconn_proto_goTypes,
		DependencyIndexes: file_ipconn_proto_depIdxs,
		MessageInfos:      file_ipconn_proto_msgTypes,
	}.Build()
	File_ipconn_proto = out.File
	file_ipconn_proto_rawDesc = nil
	file_ipconn_proto_goTypes = nil
	file_ipconn_proto_depIdxs = nil
}
