// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: linkpair.proto

package nmsg_base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Linktype int32

const (
	Linktype_anchor   Linktype = 0
	Linktype_redirect Linktype = 1
)

// Enum value maps for Linktype.
var (
	Linktype_name = map[int32]string{
		0: "anchor",
		1: "redirect",
	}
	Linktype_value = map[string]int32{
		"anchor":   0,
		"redirect": 1,
	}
)

func (x Linktype) Enum() *Linktype {
	p := new(Linktype)
	*p = x
	return p
}

func (x Linktype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Linktype) Descriptor() protoreflect.EnumDescriptor {
	return file_linkpair_proto_enumTypes[0].Descriptor()
}

func (Linktype) Type() protoreflect.EnumType {
	return &file_linkpair_proto_enumTypes[0]
}

func (x Linktype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Linktype) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Linktype(num)
	return nil
}

// Deprecated: Use Linktype.Descriptor instead.
func (Linktype) EnumDescriptor() ([]byte, []int) {
	return file_linkpair_proto_rawDescGZIP(), []int{0}
}

type Linkpair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    *Linktype `protobuf:"varint,1,req,name=type,enum=nmsg.base.Linktype" json:"type,omitempty"`
	Src     []byte    `protobuf:"bytes,2,req,name=src" json:"src,omitempty"`
	Dst     []byte    `protobuf:"bytes,3,req,name=dst" json:"dst,omitempty"`
	Headers []byte    `protobuf:"bytes,5,opt,name=headers" json:"headers,omitempty"`
}

func (x *Linkpair) Reset() {
	*x = Linkpair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkpair_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Linkpair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Linkpair) ProtoMessage() {}

func (x *Linkpair) ProtoReflect() protoreflect.Message {
	mi := &file_linkpair_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Linkpair.ProtoReflect.Descriptor instead.
func (*Linkpair) Descriptor() ([]byte, []int) {
	return file_linkpair_proto_rawDescGZIP(), []int{0}
}

func (x *Linkpair) GetType() Linktype {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Linktype_anchor
}

func (x *Linkpair) GetSrc() []byte {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Linkpair) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Linkpair) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_linkpair_proto protoreflect.FileDescriptor

var file_linkpair_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x08, 0x4c,
	0x69, 0x6e, 0x6b, 0x70, 0x61, 0x69, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6e, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x03, 0x64, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2a, 0x24,
	0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x10, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x73, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x63, 0x2f, 0x67,
	0x6f, 0x2d, 0x6e, 0x6d, 0x73, 0x67, 0x2f, 0x6e, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x3b, 0x6e, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x61, 0x73, 0x65,
}

var (
	file_linkpair_proto_rawDescOnce sync.Once
	file_linkpair_proto_rawDescData = file_linkpair_proto_rawDesc
)

func file_linkpair_proto_rawDescGZIP() []byte {
	file_linkpair_proto_rawDescOnce.Do(func() {
		file_linkpair_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkpair_proto_rawDescData)
	})
	return file_linkpair_proto_rawDescData
}

var file_linkpair_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linkpair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_linkpair_proto_goTypes = []interface{}{
	(Linktype)(0),    // 0: nmsg.base.Linktype
	(*Linkpair)(nil), // 1: nmsg.base.Linkpair
}
var file_linkpair_proto_depIdxs = []int32{
	0, // 0: nmsg.base.Linkpair.type:type_name -> nmsg.base.Linktype
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_linkpair_proto_init() }
func file_linkpair_proto_init() {
	if File_linkpair_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkpair_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Linkpair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkpair_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linkpair_proto_goTypes,
		DependencyIndexes: file_linkpair_proto_depIdxs,
		EnumInfos:         file_linkpair_proto_enumTypes,
		MessageInfos:      file_linkpair_proto_msgTypes,
	}.Build()
	File_linkpair_proto = out.File
	file_linkpair_proto_rawDesc = nil
	file_linkpair_proto_goTypes = nil
	file_linkpair_proto_depIdxs = nil
}
