// Code generated by protoc-gen-go.
// source: linkpair.proto
// DO NOT EDIT!

package nmsg_base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Linktype int32

const (
	Linktype_anchor   Linktype = 0
	Linktype_redirect Linktype = 1
)

var Linktype_name = map[int32]string{
	0: "anchor",
	1: "redirect",
}
var Linktype_value = map[string]int32{
	"anchor":   0,
	"redirect": 1,
}

func (x Linktype) Enum() *Linktype {
	p := new(Linktype)
	*p = x
	return p
}
func (x Linktype) String() string {
	return proto.EnumName(Linktype_name, int32(x))
}
func (x *Linktype) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Linktype_value, data, "Linktype")
	if err != nil {
		return err
	}
	*x = Linktype(value)
	return nil
}
func (Linktype) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type Linkpair struct {
	Type             *Linktype `protobuf:"varint,1,req,name=type,enum=nmsg.base.Linktype" json:"type,omitempty"`
	Src              []byte    `protobuf:"bytes,2,req,name=src" json:"src,omitempty"`
	Dst              []byte    `protobuf:"bytes,3,req,name=dst" json:"dst,omitempty"`
	Headers          []byte    `protobuf:"bytes,5,opt,name=headers" json:"headers,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Linkpair) Reset()                    { *m = Linkpair{} }
func (m *Linkpair) String() string            { return proto.CompactTextString(m) }
func (*Linkpair) ProtoMessage()               {}
func (*Linkpair) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *Linkpair) GetType() Linktype {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Linktype_anchor
}

func (m *Linkpair) GetSrc() []byte {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Linkpair) GetDst() []byte {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Linkpair) GetHeaders() []byte {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*Linkpair)(nil), "nmsg.base.Linkpair")
	proto.RegisterEnum("nmsg.base.Linktype", Linktype_name, Linktype_value)
}

func init() { proto.RegisterFile("linkpair.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0xcc, 0xcb,
	0x2e, 0x48, 0xcc, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0xcb, 0x2d, 0x4e,
	0xd7, 0x4b, 0x4a, 0x2c, 0x4e, 0x55, 0x8a, 0xe0, 0xe2, 0xf0, 0x81, 0x4a, 0x0a, 0x29, 0x72, 0xb1,
	0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0xf0, 0x19, 0x09, 0xeb, 0xc1, 0x55, 0xe9,
	0x81, 0x94, 0x80, 0xa4, 0x84, 0xb8, 0xb9, 0x98, 0x8b, 0x8b, 0x92, 0x25, 0x98, 0x80, 0x2a, 0x78,
	0x40, 0x9c, 0x94, 0xe2, 0x12, 0x09, 0x66, 0x30, 0x87, 0x9f, 0x8b, 0x3d, 0x23, 0x35, 0x31, 0x25,
	0xb5, 0xa8, 0x58, 0x82, 0x55, 0x81, 0x51, 0x83, 0x47, 0x4b, 0x05, 0x62, 0x32, 0x58, 0x1b, 0x17,
	0x17, 0x5b, 0x62, 0x5e, 0x72, 0x46, 0x7e, 0x91, 0x00, 0x83, 0x10, 0x0f, 0x17, 0x47, 0x51, 0x6a,
	0x4a, 0x66, 0x51, 0x6a, 0x72, 0x89, 0x00, 0x23, 0x20, 0x00, 0x00, 0xff, 0xff, 0x64, 0x13, 0x33,
	0xdf, 0x9b, 0x00, 0x00, 0x00,
}
