// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: pkt.proto

package nmsg_base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pkt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte  `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	LenFrame *uint32 `protobuf:"varint,2,opt,name=len_frame,json=lenFrame" json:"len_frame,omitempty"`
}

func (x *Pkt) Reset() {
	*x = Pkt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pkt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pkt) ProtoMessage() {}

func (x *Pkt) ProtoReflect() protoreflect.Message {
	mi := &file_pkt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pkt.ProtoReflect.Descriptor instead.
func (*Pkt) Descriptor() ([]byte, []int) {
	return file_pkt_proto_rawDescGZIP(), []int{0}
}

func (x *Pkt) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Pkt) GetLenFrame() uint32 {
	if x != nil && x.LenFrame != nil {
		return *x.LenFrame
	}
	return 0
}

var File_pkt_proto protoreflect.FileDescriptor

var file_pkt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6b, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6e, 0x6d, 0x73,
	0x67, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x03, 0x50, 0x6b, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x6e, 0x5f, 0x66,
	0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x65, 0x6e, 0x46,
	0x72, 0x61, 0x6d, 0x65,
}

var (
	file_pkt_proto_rawDescOnce sync.Once
	file_pkt_proto_rawDescData = file_pkt_proto_rawDesc
)

func file_pkt_proto_rawDescGZIP() []byte {
	file_pkt_proto_rawDescOnce.Do(func() {
		file_pkt_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkt_proto_rawDescData)
	})
	return file_pkt_proto_rawDescData
}

var file_pkt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkt_proto_goTypes = []interface{}{
	(*Pkt)(nil), // 0: nmsg.base.Pkt
}
var file_pkt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkt_proto_init() }
func file_pkt_proto_init() {
	if File_pkt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pkt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkt_proto_goTypes,
		DependencyIndexes: file_pkt_proto_depIdxs,
		MessageInfos:      file_pkt_proto_msgTypes,
	}.Build()
	File_pkt_proto = out.File
	file_pkt_proto_rawDesc = nil
	file_pkt_proto_goTypes = nil
	file_pkt_proto_depIdxs = nil
}
